# Generated by Django 3.1.3 on 2020-11-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copystockApp', '0002_copy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copy',
            old_name='sales_copy',
            new_name='text',
        ),
    ]
